### PR TITLE
#5 calculating radius to reflect points contained in it

### PR DESCRIPTION
**Pull request by smadha**
Solves https://github.com/MBoustani/Khooshe/issues/5
Calculations are done reusing present equations and their combinations

screen shot 2015-11-26 at 17 21 08

### CODE REVIEW

**Comment by chrismattmann** [comment]
+1 from me, great work @smadha !

**Comment by MBoustani** [comment]
Great work @smadha, Awesome.

**Comment by MBoustani** [comment]
@smadha is there any way to have the bubble size in all the layers except the last year?
Currently is the just showing different bubble size in first and second layer.

**Comment by smadha** [comment]
It should show on all the layers. Sometime underlying bubble count is same for two bubbles or difference between bubbles is too less and it seems they are all same sized

**Comment by MBoustani** [comment]
Got it, sounds good.

**Pull request merged**
